apiVersion: v1
kind: Service
metadata:
  name: my-python-app
spec:
  type: LoadBalancer  # or ClusterIP / NodePort, depending on your needs
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: my-python-app
