name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run Tests
      - name: Run tests
        run: pytest test_app.py

      #Debug arifacts
      - name: Debug artifacts directory
        run: |
          ls -R
          if [ -d "artifacts" ]; then
          echo "Artifacts directory exists"
          ls artifacts
          rm -rf artifact
          else
          echo "Artifacts directory does not exist"
          exit 1
           fi
      # Create Artifacts
      - name: Create artifact
        run: |
          mkdir -p artifacts
          echo "Build artifact created" > artifacts/build.txt
          
      # Upload Artifacts to S3
      - name: Upload artifact to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws s3 cp artifacts s3://myabipythonbucket/artifacts/ --recursive 

